services:
  crud-api-instance-1:
    image: go-crud-api:latest
    environment:
      - GIN_MODE=release
      - PORT=8001
    ports:
      - "8001:8001"

  crud-api-instance-2:
    image: go-crud-api:latest
    environment:
      - GIN_MODE=release
      - PORT=8002
    ports:
      - "8002:8002"

  crud-api-instance-3:
    image: go-crud-api:latest
    environment:
      - GIN_MODE=release
      - PORT=8003
    ports:
      - "8003:8003"
